quotes/quoteapp/urls.py
from django.urls import path
from . import views

app_name = 'quoteapp'

urlpatterns = [
    path('', views.main, name='main'),
    path('author/<str:quote_author>', views.author, name='author'),
    path('addauthor/', views.addauthor, name='addauthor'),
    path('addquote/', views.addquote, name='addquote'),
]

quotes/quotes/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('quoteapp.urls')),
    path('users/', include('users.urls')),
]

quotes/users/urls.py
from django.contrib.auth.views import PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path
from . import views

app_name = 'users'

urlpatterns = [
    path('signup/', views.signupuser, name='signup'),
    path('login/', views.loginuser, name='login'),
    path('logout/', views.logoutuser, name='logout'),
    path('reset-password/', views.ResetPasswordView.as_view(), name='password_reset'),
    path('reset-password/done/', PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'),
         name='password_reset_done'),
    path('reset-password/confirm/<uidb64>/<token>/',
         PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html',
                                          success_url='/users/reset-password/complete/'),
         name='password_reset_confirm'),
    path('reset-password/complete/',
         PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'),
         name='password_reset_complete'),
]

quotes/quoteapp/models.py
from django.db import models
from django.contrib.auth.models import User

class Author(models.Model):
    fullname = models.CharField(max_length=60, null=False)
    born_date = models.CharField(max_length=60, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=5000, null=False)

    def __str__(self):
        return f"{self.fullname}"

class Quote(models.Model):
    description = models.CharField(max_length=2000, null=False)
    author = models.ForeignKey(Author, on_delete=models.CASCADE)

    def __str__(self):
        return f"{self.description}"

class AuthorReg(models.Model):
    fullname = models.CharField(max_length=60, null=False)
    born_date = models.CharField(max_length=60, null=False)
    born_location = models.CharField(max_length=100, null=False)
    description = models.CharField(max_length=5000, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.fullname}"

class QuoteReg(models.Model):
    description = models.CharField(max_length=2000, null=False)
    author = models.ForeignKey(AuthorReg, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.description}"
    
class QuoteRegField(models.Model):
    description = models.CharField(max_length=2000, null=False)
    author = models.CharField(max_length=60, null=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, default=1)

    def __str__(self):
        return f"{self.description}"

quotes/quoteapp/forms.py
from django.forms import ModelForm, CharField, TextInput
from .models import QuoteRegField, AuthorReg


class QuoteForm(ModelForm):
    description = CharField(min_length=20, max_length=2000, required=True, widget=TextInput())
    author = CharField(max_length=60, min_length=10, required=True, widget=TextInput())

    class Meta:
        model = QuoteRegField
        fields = ['description', 'author']

class AuthorForm(ModelForm):
    fullname = CharField(max_length=60, min_length=10, required=True, widget=TextInput())
    born_date = CharField(max_length=60, min_length=10, required=True, widget=TextInput())
    born_location = CharField(max_length=100, min_length=10, required=True, widget=TextInput())
    description = CharField(max_length=5000, min_length=50, required=True, widget=TextInput())

    class Meta:
        model = AuthorReg
        fields = ['fullname', 'born_date', 'born_location', 'description']

quotes/quoteapp/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponseBadRequest

# Михайло, [29.03.2024 11:41]
# docker run --name quotes-postgres -p 5432:5432 -e POSTGRES_PASSWORD=214365 -d postgres
# password to superuser: 214365
# from .forms import QuoteForm, AuthorForm

from .models import Quote, Author, QuoteReg, AuthorReg, QuoteRegField
from .forms import AuthorForm, QuoteForm
# Create your views here.
def main(request):
    quotes = Quote.objects.all()
    quotes_added = QuoteReg.objects.filter(user=request.user).all() if request.user.is_authenticated else []
    return render(request, 'quoteapp/index.html', {"quotes": quotes, "quotes_added": quotes_added})



def author(request, quote_author):
    try:
        author = Author.objects.get(fullname=quote_author)
    except Author.DoesNotExist:
        # Якщо об'єкт `Author` не знайдено, шукати в моделі `AuthorReg`
        author = get_object_or_404(AuthorReg, fullname=quote_author)
    return render(request, 'quoteapp/author.html', {"author": author})


@login_required
def addauthor(request):
    if request.method == 'POST':
        form = AuthorForm(request.POST)
        if form.is_valid():
            author_reg = form.save(commit=False)
            author_reg.user = request.user
            author_reg.save()
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/addauthor.html', {'form': form})

    return render(request, 'quoteapp/addauthor.html', {'form': AuthorForm()})


@login_required
def addquote(request):
    if request.method == 'POST':
        form = QuoteForm(request.POST)
        if form.is_valid():
            add_quote = form.save(commit=False)
            add_quote.user = request.user  # Додайте користувача до цитати
            add_quote.save()
            author_name = form.cleaned_data['author']  # Отримати ім'я автора з форми
            # Спробувати знайти автора в таблиці Author
            try:
                author = Author.objects.get(fullname=author_name)
                author_type = 'Author'
            except Author.DoesNotExist:
                # Якщо автор не знайдений в таблиці Author, спробуємо знайти в таблиці AuthorReg
                try:
                    author = AuthorReg.objects.get(fullname=author_name, user=request.user)
                    author_type = 'AuthorReg'
                except AuthorReg.DoesNotExist:
                    # Якщо автор не знайдений в обох таблицях, повертаємо помилку
                    return HttpResponseBadRequest("Author not found")
            # Створити новий об'єкт QuoteReg з описом цитати та об'єктом автора
            if author_type == 'Author':
                author_reg = AuthorReg.objects.get_or_create(fullname=author.fullname, user=request.user)[0]
                QuoteReg.objects.create(description=add_quote.description, author=author_reg, user=request.user)
            else:
                QuoteReg.objects.create(description=add_quote.description, author=author, user=request.user)
            return redirect(to='quoteapp:main')
        else:
            return render(request, 'quoteapp/addquote.html', {'form': form})

    return render(request, 'quoteapp/addquote.html', {'form': QuoteForm()})



# def addquote(request):
#     if request.method == 'POST':
#         form = QuoteForm(request.POST)
#         if form.is_valid():
#             add_quote = form.save(commit=False)
#             # tag.user = request.user
#             add_quote.save()
#             author_name = form.cleaned_data['author']  # Отримати ім'я автора з форми
#             # Спробувати знайти автора в таблиці Author
#             try:
#                 author = Author.objects.get(fullname=author_name)
#             except Author.DoesNotExist:
#                 # Якщо автор не знайдений в таблиці Author, спробуємо знайти в таблиці AuthorReg
#                 try:
#                     author = AuthorReg.objects.get(fullname=author_name)
#                 except AuthorReg.DoesNotExist:
#                     # Якщо автор не знайдений в обох таблицях, повертаємо помилку
#                     return HttpResponseBadRequest("Author not found")
#             # Створити новий об'єкт QuoteReg з описом цитати та об'єктом автора
#             QuoteReg.objects.create(description=add_quote.description, author=author)
#             return redirect(to='quoteapp:main')
#         else:
#             return render(request, 'quoteapp/addquote.html', {'form': form})

#     return render(request, 'quoteapp/addquote.html', {'form': QuoteForm()})

quotes/quoteapp/templates/quoteapp/addauthor.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:addauthor' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Author fullname:
            {{ form.fullname }}
        </label>
        <span>{{ form.errors.fullname }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born date:
            {{ form.born_date }}
        </label>
        <span>{{ form.errors.born_date }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author born location:
            {{ form.born_location }}
        </label>
        <span>{{ form.errors.born_location }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/addquote.html
{% extends "quoteapp/base.html" %}

{% block content %}

<form method="POST" action="{% url 'quoteapp:addquote' %}">
    {% csrf_token %}
    <div style="padding: 10px">
        <label> Quote description:
            {{ form.description }}
        </label>
        <span>{{ form.errors.description }}</span>
    </div>
    <div style="padding: 10px">
        <label> Author of the quote:
            {{ form.author }}
        </label>
        <span>{{ form.errors.author }}</span>
    </div>
    <div class="grid">
        <button type="submit">Submit</button>
        <button type="reset" class="secondary">Reset</button>
    </div>
</form>
{% endblock %}

quotes/quoteapp/templates/quoteapp/author.html
{% extends "quoteapp/base.html" %}

{% block content %}

{% if author %}
    <div class="author-details">
        <!-- імя автору наприклад  Albert Einstein у мене на сайті Albert%20Einstein, а на оргінальному сайті Albert-Einstein -->
        <h3 class="author-title">{{author.fullname}}</h3>
        <p>
            <strong>Born:</strong>
            <span class="author-born-date">{{author.born_date}}</span>
            <span class="author-born-location">{{author.born_location}}</span>
        </p>
        <p>
            <strong>Description:</strong>
        </p>
        <div class="author-description">{{author.description}}</div>
    </div>
{% else %}
    <div class="author-details">
        <!-- імя автору наприклад  Albert Einstein у мене на сайті Albert%20Einstein, а на оргінальному сайті Albert-Einstein -->
        <h3 class="author-title">{{author_added.fullname}}</h3>
        <p>
            <strong>Born:</strong>
            <span class="author-born-date">{{author_added.born_date}}</span>
            <span class="author-born-location">{{author_added.born_location}}</span>
        </p>
        <p>
            <strong>Description:</strong>
        </p>
        <div class="author-description">{{author_added.description}}</div>
    </div>
{% endif %}

{% endblock %}

quotes/quoteapp/templates/quoteapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">
    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <h1>
            <a href="/" class="main-nav-text" style="text-decoration: none">Quotes to Scrape(django)</a>
        </h1>
    </nav>
    {% block content %} {% endblock %}
</main>
</body>
</html>

quotes/quoteapp/templates/quoteapp/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8"/>
    <title>Quotes</title>
    <link rel="stylesheet" href="https://unpkg.com/@picocss/pico@latest/css/pico.min.css"/>
    {% load static %}
    <link rel="stylesheet" href="{% static 'quoteapp/style.css' %}">
</head>
<body>
<main class="container">


    <nav style="margin-bottom: 20px; border-bottom: 2px solid; padding-left: 30px">
        <h1>
            <a href="/" class="main-nav-text" style="text-decoration: none">Quotes to Scrape(django)</a>
        </h1>
        {% if user.is_authenticated %}
        <ul>
            <li><a href="addquote/" role="button">Add Qoute</a></li>
            <li><a href="addauthor/" role="button">Add Author</a></li>
        </ul>
        <ul>
            <li>Welcome <b>{{ user.username }}!</b></li>
            <li><a href="{% url 'users:logout' %}" role="button">Logout</a></li>
        </ul>
        {% else %}
        <ul>
            <li><a href="{% url 'users:signup' %}" role="button">Sign Up</a></li>
            <li><a href="{% url 'users:login' %}" role="button">Login</a></li>
        </ul>
        {% endif %}
    </nav>

    {% if quotes_added %}
    {% for quote_added in quotes_added %}
    <div class="quote">
        <span class="text">“{{quote_added.description}}“</span>
        <span>by <small class="author">{{quote_added.author.fullname}}</small>
        <a href="{% url 'quoteapp:author' quote_added.author.fullname %}">(about)</a>
        </span>
    </div>
    {% endfor %}
    {% endif %}


    {% for quote in quotes %}
    <div class="quote">
        <span class="text">{{quote.description}}</span>
        <span>by <small class="author">{{quote.author.fullname}}</small>
        <a href="{% url 'quoteapp:author' quote.author.fullname %}">(about)</a>
        </span>
    </div>
    {% endfor %}

</main>
</body>
</html>